version: "2.1"
services:
  opfab_website:
    image: jekyll/jekyll:4.2.2
    environment:
      - JEKYLL_UID=${USER_ID}
      - JEKYLL_GID=${USER_GID}
    volumes:
      - .:/srv/jekyll
    container_name: opfab_website
    ports:
      - "4000:4000"
    command: bash -c "jekyll serve"
